version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-saas-app
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Access at http://localhost:8025
      - "1025:1025" # SMTP port

volumes:
  redis_data:
