
import {
  Boxes,
  Building2,
  Flame,
  LayoutDashboard,
  type LucideProps,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Truck,
  Users,
  Users2,
  FolderKanban,
  FileText,
  History,
  MapPin,
  Trophy,
  BarChart2,
  Briefcase,
  Calendar,
  Banknote,
  TrendingUp,
  User,
  Megaphone,
  File,
  KeyRound,
  ClipboardCheck,
  PlusCircle,
  Star,
  AlertTriangle,
  MessageSquare,
  Warehouse,
  PackageOpen,
  ArrowRightLeft,
  ListChecks,
  QrCode,
  FileBarChart,
  WandSparkles,
  HandCoins,
  Box,
  SlidersHorizontal,
  Monitor,
  ScanLine,
} from 'lucide-react';

export const Icons = {
  logo: Flame,
  dashboard: LayoutDashboard,
  vendor: Building2,
  inventory: Boxes,
  boxes: Boxes,
  shoppingCart: ShoppingCart,
  sales: ShoppingCart,
  hrms: Users2,
  users: ShieldCheck,
  supplyChain: Truck,
  truck: Truck,
  settings: Settings,
  folderKanban: FolderKanban,
  fileText: FileText,
  history: History,
  mapPin: MapPin,
  trophy: Trophy,
  barChart2: BarChart2,
  briefcase: Briefcase,
  calendar: Calendar,
  banknote: Banknote,
  trendingUp: TrendingUp,
  user: User,
  megaphone: Megaphone,
  file: File,
  keyRound: KeyRound,
  clipboardCheck: ClipboardCheck,
  plusCircle: PlusCircle,
  star: Star,
  alertTriangle: AlertTriangle,
  messageSquare: MessageSquare,
  warehouse: Warehouse,
  packageOpen: PackageOpen,
  arrowRightLeft: ArrowRightLeft,
  listChecks: ListChecks,
  qrCode: QrCode,
  fileBarChart: FileBarChart,
  wandSparkles: WandSparkles,
  handCoins: HandCoins,
  box: Box,
  package: Box,
  building2: Building2,
  users2: Users2,
  slidersHorizontal: SlidersHorizontal,
  monitor: Monitor,
  scan: ScanLine,
};
